---
- name: Check if helm is installed
  shell: "/usr/bin/which helm  >/dev/null 2>&1"
  register: helm_exist
  ignore_errors: true

- name: Install Helm on bastion VM
  when: helm_exist.rc != 0
  block:
  - name: Get helm-download-links ConsoleCLIDownload
    k8s_info:
      api_version: console.openshift.io/v1
      kind: ConsoleCLIDownload
      name: helm-download-links
    register: r_helm_cli_download
    retries: 20
    delay: 10
    ignore_errors: true
    until:
    - r_helm_cli_download.resources is defined
    - r_helm_cli_download.resources | length > 0

  - name: Extract Helm download URL from ConsoleCLIDownload
    when: r_helm_cli_download.resources | length > 0
    set_fact:
      _helm_download_url: >-
        {{ r_helm_cli_download.resources[0] | to_json | from_json
        | json_query("spec.links[?contains(href,'mirror')].href") | first }}

  - name: Download Helm binary tarball
    become: true
    get_url:
      url: "{{ _helm_download_url }}/helm-linux-amd64"
      validate_certs: false
      dest: /usr/local/bin/helm
      mode: 0755
    register: r_helm_download
    until: r_helm_download is success
    retries: 20
    delay: 10
